In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import os
pwd


NameError: name 'pwd' is not defined

In [3]:
pwd

u'/Users/marthataylor/week03_classwork'

In [6]:
from sklearn.datasets import load_breast_cancer
data=load_breast_cancer()

In [7]:
data.keys()


['target_names', 'data', 'target', 'DESCR', 'feature_names']

In [60]:
#print data['DESCR']

In [10]:
df = pd.DataFrame(data['data'],columns=data['feature_names'])

In [11]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension           ...             worst radius  \
0                 0.07871           ...                    25.38   
1                 0.05667           ...                    24.99   
2                 0.05999           ...                    23.57   
3                 0.09744           ...                    14.91   
4                 0.05883           ...                    22.54   

   worst texture  worst perimeter  worst area  worst smoothness  \
0          17.33           184.60      2019.0            0.1622   
1          23.41           158.80      1956.0            0.1238   
2          25.53           152.50      1709.0            0.1444   
3          26.50            98.87       567.7            0.2098   
4          16.67           152.20      1575.0            0.1374   

   worst compactness  worst concavity  worst concave points  worst symmetry  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   worst fractal dimension  
0                  0.11890  
1                  0.08902  
2                  0.08758  
3                  0.17300  
4                  0.07678  

[5 rows x 30 columns]

In [13]:
df.columns


Index([u'mean radius', u'mean texture', u'mean perimeter', u'mean area',
       u'mean smoothness', u'mean compactness', u'mean concavity',
       u'mean concave points', u'mean symmetry', u'mean fractal dimension',
       u'radius error', u'texture error', u'perimeter error', u'area error',
       u'smoothness error', u'compactness error', u'concavity error',
       u'concave points error', u'symmetry error', u'fractal dimension error',
       u'worst radius', u'worst texture', u'worst perimeter', u'worst area',
       u'worst smoothness', u'worst compactness', u'worst concavity',
       u'worst concave points', u'worst symmetry', u'worst fractal dimension'],
      dtype='object')

In [16]:
y=pd.DataFrame(data['target'], columns=['malignant'])

In [19]:
print y.head()
print y.describe()

   malignant
0          0
1          0
2          0
3          0
4          0
        malignant
count  569.000000
mean     0.627417
std      0.483918
min      0.000000
25%      0.000000
50%      1.000000
75%      1.000000
max      1.000000


In [27]:
from sklearn.cross_validation import cross_val_score
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [23]:
cross_val_score?

In [46]:
decision_tree=DecisionTreeClassifier()

In [47]:
y.describe()
cv_decision_tree=cross_val_score(decision_tree, df.values, y['malignant'].values, cv=5)

In [48]:
cv_decision_tree

array([ 0.90434783,  0.93913043,  0.92920354,  0.94690265,  0.91150442])

In [49]:
(np.mean(cv_decision_tree))

0.92621777606771827

In [56]:
#bagging_classifier=BaggingClassifier(decision_tree)
bagging=BaggingClassifier(decision_tree)

In [57]:
cv_bagging_classifier=cross_val_score(bagging, df.values, y['malignant'],cv=5)

In [58]:
cv_bagging_classifier

array([ 0.93913043,  0.93043478,  0.96460177,  0.96460177,  0.98230088])

In [59]:
(np.mean(cv_bagging_classifier))

0.95621392843401298

In [64]:
#if you want to pick a specific feature dont do trees
#lots of data dont use KNN
bagging.fit(df.values, y['malignant'])

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [65]:
bagging.predict(y['malignant'])

//anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


ValueError: Number of features of the model must match the input. Model n_features is 30 and input n_features is 569.

In [66]:
from sklearn.preprocessing import StandardScaler

In [67]:
standard_scaler=StandardScaler()

In [68]:
scaled_xs=standard_scaler.fit_transform(df.values)

In [69]:
scaled_xs
#makes everything average of zero and a variance of 1
#we compare difference in numbers across columns
#elephant vs a mouse

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ..., 
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [ ]:
#instead of x we will use scaled scores
#decision trees do not care the functional form a variable

In [70]:
decision_tree=DecisionTreeClassifier()
cv_decision_tree_scaled=cross_val_score(decision_tree, scaled_xs, y['malignant'].values, cv=5)

In [71]:
cv_decision_tree_scaled

array([ 0.91304348,  0.92173913,  0.91150442,  0.94690265,  0.89380531])

In [72]:
np.mean(cv_decision_tree_scaled)

0.91739899961523663

In [74]:
bagging=BaggingClassifier(DecisionTreeClassifier())
cv_bagging_classifier_scaled=cross_val_score(bagging, scaled_xs, y['malignant'] )


In [75]:
cv_bagging_classifier_scaled

array([ 0.90526316,  0.96842105,  0.92063492])

In [77]:
np.mean(cv_bagging_classifier_scaled)

0.93143971038707873

In [ ]:
#grid search
#cv but doing alot  changing hyperparameters are  
#how deep
#min number of samples it defaults to 2 max depth number of trees/split
#

In [82]:
from sklearn.grid_search import GridSearchCV
decision_tree_classifier=DecisionTreeClassifier()
parma_grid ={'max_depth':[None,1,2,3,4,5],
           'min_sample_split': [2,10,25,50,100]
           }
grid_search_dt=GridSearchCV(decision_tree_classifier, parma_grid, cv=5, verbose=10)

In [86]:
grid_search_dt.fit(df.values, y['malignant'].values())

TypeError: 'numpy.ndarray' object is not callable

In [87]:
bagging_classifier=BaggingClassifier(DecisionTreeClassifier())

In [ ]:
grid_search_bagging= GridSearchCV()

In [ ]:
#esmators number of trees
#features how many do you want to bring in
#n_jobs=-1  use all core 
