In [1]:
#!ls ~/../../assets/datasets/yelp

ls: /Users/marthataylor/../../assets/datasets/yelp: No such file or directory


In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
import sqlite3
sqlite_db='starter_code.sqlite'
conn=sqlite3.connect(sqlite_db)
c=conn.cursor()
#making a little file called stater code to hold everything

In [63]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql


In [7]:
businesses = pd.read_csv("/Users/marthataylor/businesses.csv")

In [11]:
inspections = pd.read_csv("/Users/marthataylor/inspections.csv")

In [9]:
violations = pd.read_csv("/Users/marthataylor/violations.csv")
legend = pd.read_csv("/Users/marthataylor/legend.csv")

In [10]:
businesses.head(1)


business_id              name        address           city state  \
0           10  TIRAMISU KITCHEN  033 BELDEN PL  San Francisco    CA   

  postal_code   latitude   longitude  phone_number  
0       94104  37.791116 -122.403816  +14154217044

In [12]:
inspections.head(1)


business_id  score      date     type
0           10     94  20140729  routine

In [13]:
violations.head(1)

business_id      date                                        description
0           10  20140729  Insufficient hot water or running water  [ dat...

In [15]:
legend.head(4)

Minimum_Score  Maximum_Score        Description
0              0             70               Poor
1             71             85  Needs Improvement
2             86             90           Adequate
3             91            100               Good

In [16]:
businesses.columns


Index([u'business_id', u'name', u'address', u'city', u'state', u'postal_code',
       u'latitude', u'longitude', u'phone_number'],
      dtype='object')

In [18]:
create_business="CREATE TABLE businesses  (business_id varchar PRIMARY KEY, name varchar, address varchar,city varchar,state varchar, postal_code varchar, latitude varchar, longitude varchar, phone_number varchar)"
#cursor is the cursor object
c.execute(create_business)

In [19]:
inspections.columns

Index([u'business_id', u'score', u'date', u'type'], dtype='object')

In [20]:

create_inspections = "CREATE TABLE inspections(business_ID varchar PRIMARY KEY,score varchar, date varchar, type varchar)"

c.execute(create_inspections)

Index([u'business_id', u'date', u'description'], dtype='object')

In [22]:
legend.columns

Index([u'Minimum_Score', u'Maximum_Score', u'Description'], dtype='object')

In [23]:
c.execute("CREATE TABLE legend(minimum_score varchar,maximum_score varchar, descriptions varchar);")

In [24]:
violations.columns

Index([u'business_id', u'date', u'description'], dtype='object')

In [25]:
c.execute("CREATE TABLE violations(business_id varchar PRIMARY KEY, date varchar, description varchar);")

In [26]:
conn.commit()

In [27]:
results = c.execute("SELECT * FROM sqlite_master WHERE type='table';")

In [28]:
results.fetchall()

[(u'table',
  u'businesses',
  u'businesses',
  2,
  u'CREATE TABLE businesses  (business_id varchar PRIMARY KEY, name varchar, address varchar,city varchar,state varchar, postal_code varchar, latitude varchar, longitude varchar, phone_number varchar)'),
 (u'table',
  u'inspections',
  u'inspections',
  4,
  u'CREATE TABLE inspections(business_ID varchar PRIMARY KEY,score varchar, date varchar, type varchar)'),
 (u'table',
  u'legend',
  u'legend',
  6,
  u'CREATE TABLE legend(minimum_score varchar,maximum_score varchar, descriptions varchar)'),
 (u'table',
  u'violations',
  u'violations',
  7,
  u'CREATE TABLE violations(business_id varchar PRIMARY KEY, date varchar, description varchar)')]

In [30]:
results = c.execute("SELECT * FROM inspections")

In [31]:
results

In [32]:
legend.values

array([[0, 70, 'Poor'],
       [71, 85, 'Needs Improvement'],
       [86, 90, 'Adequate'],
       [91, 100, 'Good']], dtype=object)

In [33]:
legend.as_matrix()

array([[0, 70, 'Poor'],
       [71, 85, 'Needs Improvement'],
       [86, 90, 'Adequate'],
       [91, 100, 'Good']], dtype=object)

In [34]:
legend.to_records()
#gives a list of tuples

rec.array([(0, 0, 70, 'Poor'), (1, 71, 85, 'Needs Improvement'),
 (2, 86, 90, 'Adequate'), (3, 91, 100, 'Good')], 
          dtype=[('index', '<i8'), ('Minimum_Score', '<i8'), ('Maximum_Score', '<i8'), ('Description', 'O')])

In [35]:
legend.values

array([[0, 70, 'Poor'],
       [71, 85, 'Needs Improvement'],
       [86, 90, 'Adequate'],
       [91, 100, 'Good']], dtype=object)

In [37]:
c.executemany("INSERT INTO legend VALUES (?,?,?)",legend.values)

In [38]:
conn.commit()

In [39]:
result = c.execute("SELECT * FROM legend;")

In [41]:
result.fetchall()

[(u'0', u'70', u'Poor'),
 (u'71', u'85', u'Needs Improvement'),
 (u'86', u'90', u'Adequate'),
 (u'91', u'100', u'Good')]

In [42]:
c.executemany("INSERT INTO violations VALUES (?,?,?)", violations.values)

IntegrityError: UNIQUE constraint failed: violations.business_id

In [43]:
#if add if exist then only drops it if it exists
c.execute('DROP TABLE violations;')
c.execute("CREATE TABLE violations(business_id varchar, date varchar, description varchar);")

In [44]:
c.executemany("INSERT INTO violations VALUES (?,?,?)", violations.values)

In [45]:
conn.commit()

In [46]:
result = c.execute("SELECT * FROM violations;")

In [47]:
result

In [48]:
result.fetchall()

[(u'10',
  u'20140729',
  u'Insufficient hot water or running water  [ date violation corrected: 8/7/2014 ]'),
 (u'10',
  u'20140729',
  u'Unapproved or unmaintained equipment or utensils  [ date violation corrected: 8/7/2014 ]'),
 (u'10',
  u'20140114',
  u'Inadequate and inaccessible handwashing facilities  [ date violation corrected: 1/24/2014 ]'),
 (u'10',
  u'20140114',
  u'Unclean or degraded floors walls or ceilings  [ date violation corrected: 1/24/2014 ]'),
 (u'10',
  u'20140114',
  u'Improper storage of equipment utensils or linens  [ date violation corrected: 1/24/2014 ]'),
 (u'19', u'20141110', u'Improper storage of equipment utensils or linens'),
 (u'19',
  u'20141110',
  u'Inadequate food safety knowledge or lack of certified food safety manager'),
 (u'19',
  u'20140214',
  u'Inadequately cleaned or sanitized food contact surfaces  [ date violation corrected: 2/14/2014 ]'),
 (u'19',
  u'20140214',
  u'Permit license or inspection report not posted  [ date violation correc

In [49]:
inspections.columns

Index([u'business_id', u'score', u'date', u'type'], dtype='object')

In [52]:
c.execute('DROP TABLE inspections;')

In [53]:
create_inspections = "CREATE TABLE inspections(business_ID varchar,score varchar, date varchar, type varchar)"

c.execute(create_inspections)

In [54]:
c.executemany("INSERT INTO inspections VALUES (?,?,?,?)", inspections.values)

In [55]:
conn.commit()

In [57]:
result = c.execute("SELECT * FROM inspections;")
result.fetchall()

[(u'10', u'94', u'20140729', u'routine'),
 (u'10', u'92', u'20140114', u'routine'),
 (u'19', u'94', u'20141110', u'routine'),
 (u'19', u'94', u'20140214', u'routine'),
 (u'19', u'96', u'20130904', u'routine'),
 (u'24', u'96', u'20160311', u'routine'),
 (u'24', u'96', u'20141124', u'routine'),
 (u'24', u'96', u'20140612', u'routine'),
 (u'24', u'100', u'20131118', u'routine'),
 (u'31', u'98', u'20151204', u'routine'),
 (u'31', u'100', u'20140908', u'routine'),
 (u'45', u'78', u'20160104', u'routine'),
 (u'45', u'94', u'20140909', u'routine'),
 (u'45', u'94', u'20131209', u'routine'),
 (u'48', u'92', u'20140523', u'routine'),
 (u'48', u'90', u'20131101', u'routine'),
 (u'50', u'100', u'20140402', u'routine'),
 (u'50', u'100', u'20131002', u'routine'),
 (u'54', u'100', u'20150526', u'routine'),
 (u'54', u'92', u'20140325', u'routine'),
 (u'54', u'96', u'20131008', u'routine'),
 (u'56', u'88', u'20151222', u'routine'),
 (u'56', u'98', u'20141117', u'routine'),
 (u'56', u'100', u'20140423',

In [50]:
businesses.columns

Index([u'business_id', u'name', u'address', u'city', u'state', u'postal_code',
       u'latitude', u'longitude', u'phone_number'],
      dtype='object')

In [59]:
c.executemany("INSERT INTO businesses VALUES (?,?,?,?,?,?,?,?,?)", businesses.values)

IntegrityError: UNIQUE constraint failed: businesses.business_id

In [60]:
result = c.execute("SELECT * FROM businesses;")
result.fetchall()

[(u'10',
  u'TIRAMISU KITCHEN',
  u'033 BELDEN PL',
  u'San Francisco',
  u'CA',
  u'94104',
  u'37.791116',
  u'-122.403816',
  u'+14154217044'),
 (u'19',
  u'NRGIZE LIFESTYLE CAFE',
  u'1200 VAN NESS AVE, 3RD FLOOR',
  u'San Francisco',
  u'CA',
  u'94109',
  u'37.786848',
  u'-122.421547',
  u'+14157763262'),
 (u'24',
  u'OMNI S.F. HOTEL - 2ND FLOOR PANTRY',
  u'500 CALIFORNIA ST, 2ND  FLOOR',
  u'San Francisco',
  u'CA',
  u'94104',
  u'37.792888',
  u'-122.403135',
  u'+14156779494'),
 (u'31',
  u"NORMAN'S ICE CREAM AND FREEZES",
  u'2801 LEAVENWORTH ST ',
  u'San Francisco',
  u'CA',
  u'94133',
  u'37.807155',
  u'-122.419004',
  None),
 (u'45',
  u"CHARLIE'S DELI CAFE",
  u'3202 FOLSOM ST ',
  u'San Francisco',
  u'CA',
  u'94110',
  u'37.747114',
  u'-122.413641',
  u'+14156415051'),
 (u'48',
  u"ART'S CAFE",
  u'747 IRVING ST ',
  u'San Francisco',
  u'CA',
  u'94122',
  u'37.764013',
  u'-122.465749',
  u'+14156657440'),
 (u'50',
  u'SUSHI ZONE',
  u'1815  MARKET ST. ',
  u'

In [62]:
c.execute("SELECT COUNT (*)  FROM businesses;").fetchall()

[(3177,)]

In [66]:
%sql sqlite:///starter_code.sqlite

u'Connected: None@starter_code.sqlite'